<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Navegador no suportado_main</name>
   <tag></tag>
   <elementGuidId>3b83bf2c-934c-44bb-9c4e-ef85c6db3acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;main&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>cbbe34fd-f59b-4c00-9280-29f9c38d6547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>8fe200ac-06b2-46ad-af04-f1f9947817d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>cisMain.jsp?language=PTG</value>
      <webElementGuid>97967882-595f-4ba0-a5b6-25f30d05d676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5fe9ad96-5484-456b-aed5-b789e543435b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Estrutura Principal</value>
      <webElementGuid>683938c9-768a-4790-8678-d0e2546077b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[@class=&quot;oraDesktop&quot;]/frame[1]</value>
      <webElementGuid>a714a601-204b-4d4d-a1d4-a804bfb822f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='main']</value>
      <webElementGuid>992c44b2-4568-429e-b8cb-9d6562bcb069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>6d111a4a-d16c-4dfd-8505-8f3fc9695907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'main' and @src = 'cisMain.jsp?language=PTG' and @title = 'Estrutura Principal']</value>
      <webElementGuid>91336956-65b4-4572-8046-fbcf3041b456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
