<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Formulrios</name>
   <tag></tag>
   <elementGuidId>b24385bd-25cd-48b9-9b7b-c6afea56915b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='CI_MAINMENU_topMenuItem0x4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CI_MAINMENU_topMenuItem0x4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d00e2250-e13a-4613-9c00-1fe3c90bd3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menuItem activeMenuItem</value>
      <webElementGuid>a222f130-5c1d-4a8c-82e0-c0065c7482e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cca70cbd-2397-440e-8c27-3d4762579350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1e6827b6-1c26-40a9-bd03-d93447bde2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menuobj</name>
      <type>Main</type>
      <value>CI_MAINMENU</value>
      <webElementGuid>008826b7-436b-4e96-8df1-7b82ef9f7d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isleaf</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ba46004-2950-4649-8a98-86722e9091d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menutype</name>
      <type>Main</type>
      <value>MAIN</value>
      <webElementGuid>ab1a3349-2ccd-4f56-bfd3-f897e71cb71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ouaf.context.expandSubMenu(true)</value>
      <webElementGuid>57093249-b2c3-48ec-8b78-80dd4f7e4181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>ouaf.context.expandSubMenu(false)</value>
      <webElementGuid>326bc85a-79bb-4c5d-82cb-6d96f6682ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ouaf.context.onMenuKeyPress(event)</value>
      <webElementGuid>ee310264-cfd6-4912-a841-92ea607f5302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96ddbbd8-3699-44fb-9854-9b6185460bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-submenuname</name>
      <type>Main</type>
      <value>CI_FORM</value>
      <webElementGuid>50a5140a-46ae-4128-a98e-1e54ac8c66d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CI_MAINMENU_topMenuItem0x4</value>
      <webElementGuid>f8a9b9ce-abdd-489a-bb07-15a62042e26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulários</value>
      <webElementGuid>8e83a6d7-4827-4c64-b375-cbc998114793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CI_MAINMENU_topMenuItem0x4&quot;)</value>
      <webElementGuid>71e98a3a-0589-4c17-9fe1-1f2261f2ac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIGT/Page_Pesquisa a 360 Graus/frame_Navegador no suportado_main</value>
      <webElementGuid>b28ff323-ab39-4b07-9b6c-9601fec02e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='CI_MAINMENU_topMenuItem0x4']</value>
      <webElementGuid>acfb0ea5-9b8b-478e-8b8a-db6240ddbb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuDiv_0']/ul/li[3]</value>
      <webElementGuid>e4ca412b-42b3-4d46-a234-e9fb4d8c8e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastro de Contribuinte'])[1]/following::li[1]</value>
      <webElementGuid>41b723d5-bd44-4e83-bbbd-ada7b3cc2185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulário de Cadastro'])[1]/following::li[3]</value>
      <webElementGuid>90a43ed1-660c-4d2d-9c92-6cc86bbf455b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestão de Trabalho'])[1]/preceding::li[1]</value>
      <webElementGuid>e01a090a-97a7-429b-a155-4c8934f70213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>06ded227-a14f-4e02-8221-d131dad41726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'CI_MAINMENU_topMenuItem0x4' and (text() = 'Formulários' or . = 'Formulários')]</value>
      <webElementGuid>b2258acb-9cac-4020-9f5f-e8a021ef08c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
