<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Menu</name>
   <tag></tag>
   <elementGuidId>30644d41-8aeb-47c7-ab02-1ea627f5a569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='IM_menuButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IM_menuButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc3cca89-95d9-416f-a06b-0419f814d313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IM_menuButton</value>
      <webElementGuid>dacf2c5e-aad2-4b5d-a70b-6b036649c248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ouafButton toolbarButton simpleToolbarButton menuImg</value>
      <webElementGuid>b8aafcda-365b-4518-9d59-ef37c654363a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menu (Ctrl+Alt+M)</value>
      <webElementGuid>309147c1-80b0-4092-8e7a-38a96808b0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doClose();onTopMenuClick('CI_MAINMENU', event);</value>
      <webElementGuid>2abdcc51-fa17-4aaf-8740-61c6c65db4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>onToolbarButtonKeyPress(event)</value>
      <webElementGuid>dbd366a5-2261-496b-82dc-2be2164c3188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>934b9687-1960-40fd-a975-56a3c0e6e937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>33cd7a92-6a15-4ff3-836e-74e02ed1908c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>e5ebf720-7815-4e6f-92b8-040540940899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM_menuButton&quot;)</value>
      <webElementGuid>303a727c-dfa7-469e-b4fe-9d29da28a8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIGT/Page_Pesquisa a 360 Graus/frame_Navegador no suportado_main</value>
      <webElementGuid>128949a4-deab-4d92-b4df-4a0ef756c8a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='IM_menuButton']</value>
      <webElementGuid>573c8128-0236-4811-811f-855ebdaec9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leftToolbarArea']/span[3]</value>
      <webElementGuid>fdcbafaa-23f2-405b-a62a-ace805551e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Página Principal'])[1]/following::span[1]</value>
      <webElementGuid>5b314fd2-714a-4ebc-b732-a86974ba5b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites'])[1]/following::span[2]</value>
      <webElementGuid>1f7906e7-a2db-409f-a86d-0677fed3c7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>5479f171-576a-4b47-8589-05e9b97f8f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::span[2]</value>
      <webElementGuid>e1517332-a086-4124-9663-4360eb95feb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>3440a352-530a-4225-bf0d-edde56d4d3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>4ebceae9-6445-47cd-bcbe-8f91c8e9b8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'IM_menuButton' and @title = 'Menu (Ctrl+Alt+M)' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>b504c378-b978-4638-bb8c-a7ea68767135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
