<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Gesto de Patrimnio  Consulta de Registo _46a9f4</name>
   <tag></tag>
   <elementGuidId>7ecd2225-476f-441e-ab15-7a14b600b5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/main/div/div/ul/li[15]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>e9d07fce-b6df-406d-a17d-837d3ff9162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-left</value>
      <webElementGuid>0b3658e0-1740-46dc-ba48-9b6faeef1e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gestão de Patrimônio | Consulta de Registo de Imóvel (Número Matricial Antigo)</value>
      <webElementGuid>c6c52d87-3dc2-4715-b01b-a24815b71af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row-md&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;panel panel-default clearfix&quot;]/ul[@class=&quot;text-center clearfix container-box-shadow margin-top-twenty-five&quot;]/li[@class=&quot;col-sm-6 fixed-height margin-bottom-twenty&quot;]/div[@class=&quot;box-shadow fixed-height no-video&quot;]/div[@class=&quot;clearfix&quot;]/h4[@class=&quot;text-left&quot;]</value>
      <webElementGuid>df1c5ca2-039d-47b5-839c-422ed2913cc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/div/div/ul/li[15]/div/div/h4</value>
      <webElementGuid>e5fcd005-25ef-49ad-b7db-69114672498f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baixar PDF'])[14]/following::h4[1]</value>
      <webElementGuid>549fcfb9-96c9-425e-9b85-bfa72fa48ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestão de Património | Gestão de Contratos de Arrendamento de Imóveis'])[1]/following::h4[1]</value>
      <webElementGuid>17294014-53c4-46d9-9a2d-57ec3a920544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baixar PDF'])[15]/preceding::h4[1]</value>
      <webElementGuid>1e638c20-46c1-4cab-a06f-73de216656fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nova Declaração de Imposto Industrial'])[1]/preceding::h4[1]</value>
      <webElementGuid>a5b97447-1635-46e1-87f9-1ebc35e399ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gestão de Patrimônio | Consulta de Registo de Imóvel (Número Matricial Antigo)']/parent::*</value>
      <webElementGuid>fabe7f04-db9b-4499-b4ea-0f7ffef49f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/div/div/h4</value>
      <webElementGuid>922a8fd0-b4ad-4c48-b39c-9076f764ac81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Gestão de Patrimônio | Consulta de Registo de Imóvel (Número Matricial Antigo)' or . = 'Gestão de Patrimônio | Consulta de Registo de Imóvel (Número Matricial Antigo)')]</value>
      <webElementGuid>56ed927d-87e1-471a-9bf3-5ece68bc3a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
