<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Conta_anTLZ1Refresh</name>
   <tag></tag>
   <elementGuidId>63b48434-1ba6-47e9-a5a8-187b5b15107d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anTLZ1Refresh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anTLZ1Refresh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e982e3a3-5753-4203-adac-07bd25f482b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>ffd1da95-b1d2-4a55-97f9-b02910027ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>4ef38b94-440f-4a4f-b0f9-787cb4e31dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton</value>
      <webElementGuid>0f2b2870-7c9b-4297-8935-befbc3b2bb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4baf0748-e540-4930-a137-f229e12ee605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>3d503080-7e6a-4921-82f2-a456183ceff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>refreshZone1();</value>
      <webElementGuid>8bc399c4-6681-464f-a13e-8e87200eedad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3794c4d7-a03f-4b9c-a391-daa199a29fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anTLZ1Refresh&quot;)</value>
      <webElementGuid>466e4024-5c2c-4f82-a45a-ba830f3a070a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anTLZ1Refresh']</value>
      <webElementGuid>63cd1ea2-5e81-4dc1-b33e-c154cbfcabbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='multiQueryFilterBody1']/tbody/tr[2]/td/input</value>
      <webElementGuid>4c34c498-f2a0-486e-a485-a14ab37543d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>1f2b09aa-1ef2-4866-be68-6f07cdbcc887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'anTLZ1Refresh' and @name = 'anTLZ1Refresh' and @type = 'button']</value>
      <webElementGuid>8094d16c-de41-4161-a598-67ff366fc76e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
