<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_N Identificao_idValue</name>
   <tag></tag>
   <elementGuidId>82bd2f09-af2c-4eab-ba48-0c5f50761378</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd12b1d0-f5b7-4ae3-a6fb-c6bb4a6d5018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idValue</value>
      <webElementGuid>8cff52ff-d9b2-4a43-943e-a8f3d6ddfa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraInput oraDefault</value>
      <webElementGuid>4ab1f6b4-e3f9-41d7-a97e-2975012d5cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>idValue</value>
      <webElementGuid>718c271b-f2d4-4556-815b-2e02c921eb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:16</value>
      <webElementGuid>cf83f509-d9d6-46a8-b4d4-5cd00d9648bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>idValue</value>
      <webElementGuid>be85e0d5-84ca-4706-92c4-0369db283d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>14cd3814-0de2-40be-a103-4885149993f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>fac0b0f8-8bbe-4169-975a-49752e4a72e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>99ea58ef-901b-4453-9411-0aa60a2da919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idValue&quot;)</value>
      <webElementGuid>31fe6daa-7e26-48a4-8908-6c3a4b9d4ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idValue']</value>
      <webElementGuid>1b50f988-66f6-490a-81a1-d5f5e9046cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tableRow3']/td[2]/input</value>
      <webElementGuid>7db149de-d1e0-4b63-9997-6bce3926ef2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>8793708a-4cd8-4be6-a2a2-b5191740676e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idValue']</value>
      <webElementGuid>1d588f8d-59ce-4629-b970-c680536b8cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
