<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bilhete de IdentidadeAssento de Nasc_b550c9</name>
   <tag></tag>
   <elementGuidId>9363d1af-fac0-4eb2-8adf-e2931ac7925e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='idType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a968815-753b-47cc-b5e2-be70467848c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>idType</value>
      <webElementGuid>8ec6182b-d581-4348-9794-9a418e138a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselect</name>
      <type>Main</type>
      <value>bs:CM-RetrieveIdTypeList</value>
      <webElementGuid>69d9c519-d947-4e49-9505-6a3707bb2e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselectout</name>
      <type>Main</type>
      <value>valuePath:results/idType;descPath:results/description</value>
      <webElementGuid>48f53c07-3ac4-4c0b-9922-25ff791c23ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idType</value>
      <webElementGuid>5b421fcb-aadd-43f6-8f21-b392ca34dc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:8</value>
      <webElementGuid>667ece02-72c7-4e91-b96b-9993b2bf4542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>2c2ffec3-146c-4b6e-83df-dc966ae6c562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>idType</value>
      <webElementGuid>0451381a-be2f-4dc8-b869-511c40e58de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>c69acda5-414f-4d22-bcfa-53a9f2dde0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>07e5b561-7f96-4aa5-9258-498abf43ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor</value>
      <webElementGuid>fe392fca-04b0-428f-96c5-361113d88350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idType&quot;)</value>
      <webElementGuid>6eee8967-8ecd-40d4-bbf5-ff823bc06f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='idType']</value>
      <webElementGuid>7f3126d6-9dfa-49ef-b6ea-852bb9e04ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tableRow2']/td[2]/select</value>
      <webElementGuid>881d6d09-ecf9-4545-b12e-4db6145c2c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Identificação'])[1]/following::select[1]</value>
      <webElementGuid>9f2c3624-5a37-4d2b-a159-fb7742c05948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome da Pessoa'])[1]/following::select[1]</value>
      <webElementGuid>4dc14a0f-eb1f-4c15-84ef-f7eed656f8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nº Identificação'])[1]/preceding::select[1]</value>
      <webElementGuid>b1638ef4-df79-4a03-b7b9-796bbebd3c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conta'])[1]/preceding::select[1]</value>
      <webElementGuid>6ec71d9d-3626-447e-9b46-a896c1bf6bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7765e5d4-4ec9-437e-8d92-f0317bb26cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'idType' and (text() = '
Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor' or . = '
Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor')]</value>
      <webElementGuid>bb6ec0b5-2537-48d0-8609-a461c38825e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
