<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_visualizar</name>
   <tag></tag>
   <elementGuidId>e0ad4184-4123-4738-8f0b-69a3d66a14db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmRegisterUser:accordion:downloadDocumentoIdentificacao']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-text.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1625e2be-d701-4552-acd5-b756d48ff3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>2018897c-276b-4e5d-b87a-30bed96664f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>visualizar</value>
      <webElementGuid>0efb87bf-49bf-4ae1-a32d-b11fe9a04961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRegisterUser:accordion:downloadDocumentoIdentificacao&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>7c686111-19f1-4966-9c29-81ef59dcd916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e03360bb-4898-45a6-9190-b077c48ee402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>d06870ca-3284-483d-97d4-2796d4031077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>visualizar</value>
      <webElementGuid>74323ec4-18f1-4a42-b207-5410d1390bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRegisterUser:accordion:downloadDocumentoIdentificacao&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>c14dbd21-21e4-4888-a941-5c9224b27532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmRegisterUser:accordion:downloadDocumentoIdentificacao']/span[2]</value>
      <webElementGuid>867fbc2f-c6ab-4ac4-838a-3a861de3c550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balancete Fecho - Analitico (3) (1)-2.pdf'])[1]/following::span[2]</value>
      <webElementGuid>13cc8066-e165-4638-be72-51d0e3ed6871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telefone: *'])[1]/following::span[4]</value>
      <webElementGuid>4e4668b7-90e3-424b-99d5-deb74f643901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/preceding::span[3]</value>
      <webElementGuid>f7ecbd48-fc53-4ad0-a578-133456cede42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voltar'])[1]/preceding::span[5]</value>
      <webElementGuid>f365529b-6e0b-4eec-81de-3012571cb6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='visualizar']/parent::*</value>
      <webElementGuid>f2d2a5c6-2e83-4b4c-a6b5-5f3c22bc206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]</value>
      <webElementGuid>b6a4a297-8346-4fc5-81d0-e29c0577bf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'visualizar' or . = 'visualizar')]</value>
      <webElementGuid>494cce24-5f4f-4811-8093-d3935dc45d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cópia do Bi do Miguel.pdf'])[1]/following::span[2]</value>
      <webElementGuid>93dfd9c0-5768-4642-b3ca-b6ca4e9e9e40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
