<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by NIF_frmRepresentationsdtRep_73fa99</name>
   <tag></tag>
   <elementGuidId>eca02b33-84f5-499f-90e8-6fc705ab5f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmRepresentations:dtRepresentation:ftlNifDC:filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab32c12a-8e55-40ec-a9a2-908d921994c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmRepresentations:dtRepresentation:ftlNifDC:filter</value>
      <webElementGuid>285fc091-ce76-4b1d-a9f3-76af7e0a21cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmRepresentations:dtRepresentation:ftlNifDC:filter</value>
      <webElementGuid>e0c9e2fc-d7b7-4a9d-bd84-cb827d123e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>f209f21d-27e0-4da1-8190-7c14435e61f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d5c215c1-7bb7-4c5a-85d4-fbc4257c6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>frmRepresentations:dtRepresentation:ftlNifDC:filter_label</value>
      <webElementGuid>8a86b410-0dd4-42ae-921f-d40e64ddb196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b1aaa02f-457b-4161-b05d-51febdc83b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66179ac0-5f57-454a-940a-6eb3a4515605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6eb3d68-695e-4c51-8a77-c4b6218e1970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRepresentations:dtRepresentation:ftlNifDC:filter&quot;)</value>
      <webElementGuid>d8669a4e-9896-445a-ac8e-4b7f5d88d489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmRepresentations:dtRepresentation:ftlNifDC:filter']</value>
      <webElementGuid>7ecbcafc-60f2-40c1-b795-895e758080f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='frmRepresentations:dtRepresentation:ftlNifDC']/input</value>
      <webElementGuid>21e859f9-86d5-4f74-b762-c1412d446313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>dc18a70f-9469-4cd4-ab2a-a7de1aa551f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmRepresentations:dtRepresentation:ftlNifDC:filter' and @name = 'frmRepresentations:dtRepresentation:ftlNifDC:filter']</value>
      <webElementGuid>1bd2135b-4577-481b-968b-ba4c2bde77ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
