<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seleccionar</name>
   <tag></tag>
   <elementGuidId>9851abc8-eb42-4e57-b027-ebbc348d9cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmRepresentations:dtRepresentation:0:btnSelect']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c94fca33-ffd6-4bec-bc25-5ed7dd8acd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>aa2bd9f5-e343-4c4b-8048-46a58a00ad77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccionar</value>
      <webElementGuid>03117c35-54aa-438c-a1bf-6dae44444c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRepresentations:dtRepresentation:0:btnSelect&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>0a6b13a0-28ba-476a-a6c9-9ae5c26a27a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmRepresentations:dtRepresentation:0:btnSelect']/span</value>
      <webElementGuid>28dd7bcf-ed6a-4e09-a737-4344da48fcfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIGITAL FOCUS - PROJECTOS EDUCATIVOS, LDA'])[1]/following::span[1]</value>
      <webElementGuid>97d7b488-40ec-455a-bb88-c9e7108cd26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by Contribuinte'])[1]/following::span[3]</value>
      <webElementGuid>211a789a-dc80-4551-a5b3-ef6094ef5be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/preceding::span[1]</value>
      <webElementGuid>ad30840e-8d0f-4732-a43e-1f9531895cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/preceding::span[2]</value>
      <webElementGuid>c630d5f1-6aa4-4162-a1b5-0417f6157c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seleccionar']/parent::*</value>
      <webElementGuid>1a3da205-72cd-4df7-98e0-152393c00f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button/span</value>
      <webElementGuid>0f51cb15-2386-4e44-b2f0-6e88542ffe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Seleccionar' or . = 'Seleccionar')]</value>
      <webElementGuid>6ce8b010-fabc-430d-b46f-7f935e1b7c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
