<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_btnLoginDC</name>
   <tag></tag>
   <elementGuidId>31f69da9-e861-4eac-9387-0abf37d194ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnLoginDC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnLoginDC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd7fab8a-04f6-4fa1-8fc0-cb588c194042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnLoginDC</value>
      <webElementGuid>05a97003-7018-47cf-b3d9-dd1b642d51ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnLoginDC</value>
      <webElementGuid>4ce253ce-17a5-422f-ad15-865f7581d507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b7edbd11-3433-4d63-8126-e9d4bfdcf009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Iniciar Sessão</value>
      <webElementGuid>a6aaa026-a762-4229-9d65-f52da9063d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn margin-bottom-fitteen</value>
      <webElementGuid>326a715c-cf1f-4e25-bab4-5e858f53d589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnLoginDC&quot;)</value>
      <webElementGuid>eec4b907-ecb7-4b82-aef4-7ed6c32a8424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnLoginDC']</value>
      <webElementGuid>0013df42-3d1b-4fea-96f4-bc604f0881b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/form/div/div[3]/input</value>
      <webElementGuid>111702a3-642d-4e92-94e8-eabdea3e56e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>99ef83a9-a882-4d71-a3de-c8df52f60b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnLoginDC' and @name = 'btnLoginDC' and @type = 'submit']</value>
      <webElementGuid>f1519450-cf6c-474f-b1de-82991c88b77d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
