<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_j_password</name>
   <tag></tag>
   <elementGuidId>086370db-20c0-43ea-b577-8d5740378d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>488063f8-c613-463a-a464-c4459ea5f867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0db702e1-0742-47c7-84c8-0946c310fec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>3a9f8a18-3bdf-45c0-b409-d0eb1e447972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>e4191c28-ad6d-4d8b-a0ed-8723c75af5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1636f940-93a9-43b1-b4c7-5790c5a7974e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Palavra Passe</value>
      <webElementGuid>c81307c4-cc14-4f9f-822a-6f3fcdc713c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_password&quot;)</value>
      <webElementGuid>4696e6c6-22ac-44a1-9d64-0c60ee925f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_password']</value>
      <webElementGuid>3dacc504-fc8b-48d6-9381-61518a7368db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/form/div/div[2]/input</value>
      <webElementGuid>8333c621-5341-4da5-aef3-c478fa188d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>fdfd59d2-2de0-4b73-b73c-d3bda87a4ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'j_password' and @name = 'j_password' and @placeholder = 'Palavra Passe']</value>
      <webElementGuid>6b631650-9377-4ee0-aeaf-9a0be4b7a8af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
