<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Navegador no suportado_main</name>
   <tag></tag>
   <elementGuidId>e47cc518-5a0b-41a9-a961-77d78f154ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;main&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>305fd970-d74b-44b2-833e-b5089cb71f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>4e8711c9-85e2-44d3-a9fd-817ce1f41cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>cisMain.jsp?language=PTG</value>
      <webElementGuid>6f70f8cf-c40b-4058-96a9-01751ba1c671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a22e1aee-5d53-46c1-93a4-ec353e8a410d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Estrutura Principal</value>
      <webElementGuid>e23345d5-b8f0-44db-ac27-668327baf13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[@class=&quot;oraDesktop&quot;]/frame[1]</value>
      <webElementGuid>cb839bf3-bb46-4f7c-bc7b-839055eae019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='main']</value>
      <webElementGuid>87d6e076-5dbe-42d4-887e-2c476e3bb0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>edffb3a7-137f-42cf-8c19-5b9d1e15cbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'main' and @src = 'cisMain.jsp?language=PTG' and @title = 'Estrutura Principal']</value>
      <webElementGuid>a07babcb-c952-4b78-a803-5dc3a32fd9e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
