<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Consulta de Formulrios Fiscais_tabPage</name>
   <tag></tag>
   <elementGuidId>b7248bfb-1b68-4bdb-8d3a-1c3479945793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tabPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62467f0f-d27e-4801-bb4d-a6ea51d902bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabPage</value>
      <webElementGuid>89801f1d-c21b-4ac2-8f88-0be0631d8845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabPage</value>
      <webElementGuid>bdc300d6-9c91-4152-a4a1-444524c12572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Página do Tipo Separador</value>
      <webElementGuid>776b0710-0bcb-4e25-9134-d8764592b85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>uiPage/c1txfrmqPage?language=PTG</value>
      <webElementGuid>edba513a-aed9-4ff1-a435-84ad324e9a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>f364ebfe-d43d-49de-b9be-f129fad335ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabPage&quot;)</value>
      <webElementGuid>85685a08-7271-4d19-a517-b56f38ae213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIGT/Page_Consulta de Formulrios Fiscais/frame_Navegador no suportado_main</value>
      <webElementGuid>27decd96-3d29-4656-a1cb-9ed64d00a046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tabPage']</value>
      <webElementGuid>51ccbefe-e7cf-4480-9243-cc083fc8222f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabDiv']/iframe</value>
      <webElementGuid>1631cbbd-b4b4-432f-a6ed-36f96806593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta de Formulários Fiscais'])[1]/following::iframe[2]</value>
      <webElementGuid>df0f0c49-ced3-4719-b203-0d74b7c45703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Painel'])[1]/preceding::iframe[2]</value>
      <webElementGuid>2f7c1003-b072-4107-986f-107038d0123a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[1]/preceding::iframe[2]</value>
      <webElementGuid>86dc07cf-f2a9-40d0-b34f-80abc88f0f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/iframe</value>
      <webElementGuid>4a1ff6b1-4840-4cf6-8921-46398706c299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'tabPage' and @name = 'tabPage' and @title = 'Página do Tipo Separador' and @src = 'uiPage/c1txfrmqPage?language=PTG']</value>
      <webElementGuid>2380c6ac-67b5-4970-8173-58851c8f02e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
