<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valor da ID_anTLZ1Refresh</name>
   <tag></tag>
   <elementGuidId>89bc269e-2720-4325-a12d-482b386abccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anTLZ1Refresh']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#anTLZ1Refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f51ce7f3-8a3c-4e47-a5e4-0566201625e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>b529d36a-b9c4-483e-a1f9-997bd574f11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anTLZ1Refresh</value>
      <webElementGuid>3d1f8bb1-6818-4849-a9f1-69cea2e14b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraButton</value>
      <webElementGuid>589c7b66-5ed1-48ab-85d4-c5e93dae84aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4799cd8c-87a7-4543-b230-b9b696b0179f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>b02748b4-a4e8-444c-936f-25b83bd72291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>refreshZone1();</value>
      <webElementGuid>e4b7b899-0420-469d-80bd-94532b242e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4b9810e3-ff36-4507-966d-2104812e61c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anTLZ1Refresh&quot;)</value>
      <webElementGuid>6e8bc1b6-0704-47a8-920d-42ad62f3829e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIGT/Page_Consulta de Formulrios Fiscais/iframe_Consulta de Formulrios Fiscais_tabPage</value>
      <webElementGuid>2cac1a74-47c7-4af8-bafa-91359de2b0dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anTLZ1Refresh']</value>
      <webElementGuid>e99e10cb-4fd7-4ff5-a61b-e93cc2c47149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='multiQueryFilterBody1']/tbody/tr[2]/td/input</value>
      <webElementGuid>7b6659f4-33b9-44f1-8deb-7ad22fadb47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>321388d6-a9ec-416e-a15b-9f2481c0924a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'anTLZ1Refresh' and @name = 'anTLZ1Refresh' and @type = 'button']</value>
      <webElementGuid>7bb448a3-4031-456d-b2f8-0355e0ad153b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
