<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bilhete de IdentidadeAssento de Nasc_b550c9</name>
   <tag></tag>
   <elementGuidId>9ff35040-b4b5-4df2-a21c-eb6513d586cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='personIdType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personIdType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ee2ae7ad-9535-43cd-a8d0-645f8b6effd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselect</name>
      <type>Main</type>
      <value>bs:CM-RetrieveIdTypeList</value>
      <webElementGuid>7ae1960e-373e-4bf9-aa7d-2250c5125626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraselectout</name>
      <type>Main</type>
      <value>valuePath:results/idType;descPath:results/description</value>
      <webElementGuid>d2d46ec5-44cb-4f89-a697-14b15dfa0eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personIdType</value>
      <webElementGuid>d53e89c1-9d2a-40d3-85eb-57facfae0a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>orafield</name>
      <type>Main</type>
      <value>idType</value>
      <webElementGuid>d039c602-6b21-4b12-8418-156512bcf109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>formatIdNumber();</value>
      <webElementGuid>9f3bded9-ba09-435a-b1b6-483fe6f3b9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oratype</name>
      <type>Main</type>
      <value>string;precision:8</value>
      <webElementGuid>db5f4d8d-d054-42cc-8f8c-5753d019ea89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataexplorerdropdownstate</name>
      <type>Main</type>
      <value>Collapsed</value>
      <webElementGuid>baf818a5-d76d-42bc-97db-be8286754bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oraerrorelement</name>
      <type>Main</type>
      <value>idType</value>
      <webElementGuid>238357b7-351e-44a3-aaeb-ad19ba9e01a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oraDefault</value>
      <webElementGuid>93b5c43d-5230-42cc-b4fa-c5e680c1f9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>743e5de9-d8fc-4092-b2fd-56985233ad9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor</value>
      <webElementGuid>5f834872-31b9-4a34-8df4-d4e944658d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personIdType&quot;)</value>
      <webElementGuid>2a798720-43e4-4679-baee-51980017c137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SIGT/Page_Consulta de Formulrios Fiscais/iframe_Consulta de Formulrios Fiscais_tabPage</value>
      <webElementGuid>9d1d025a-906e-48ba-9134-c7cbba4cc4b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='personIdType']</value>
      <webElementGuid>0e70823e-5668-47fd-a6b6-afe97ca13e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='filterUIFields']/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>65c01760-5f84-4991-a301-63f671e04d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de ID'])[1]/following::select[1]</value>
      <webElementGuid>5706358e-9d13-43b0-ad91-1c42eaf108f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Último Nome'])[1]/following::select[1]</value>
      <webElementGuid>7d6aac8b-d4e5-4f5b-87ca-df81cd980457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor da ID'])[1]/preceding::select[1]</value>
      <webElementGuid>f7353340-c5aa-4727-94a6-a028b17db1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'personIdType', '&quot;', ')')])[1]/preceding::select[2]</value>
      <webElementGuid>c61d98f0-f838-4ce8-b112-277d1bf78491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>bb533502-0466-467a-b4ee-23f75f05e485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'personIdType' and (text() = '

Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor' or . = '

Bilhete de IdentidadeAssento de NascimentoCertidão de NascimentoNº de Registo ComercialCarta de ConduçãoIdentificação de Cidadão EstrangeiroBI LegadoNIFOutroPassaporteIdentificação de Funcionário PúblicoCartão de RefugiadoCartão de ResidenteCartão de Eleitor')]</value>
      <webElementGuid>92a5387c-990d-45e9-a4e3-c8e294482ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
