<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Editar (1)</name>
   <tag></tag>
   <elementGuidId>6cc7dad0-48f3-4526-a82f-c63c36c20edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmWithholdingMap:recipients:2:j_id_90']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7638028f-415f-41bf-8755-a0391c62d543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmWithholdingMap:recipients:2:j_id_90</value>
      <webElementGuid>075edccc-7224-41c4-b288-f84c40e88baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmWithholdingMap:recipients:2:j_id_90</value>
      <webElementGuid>dda859b8-0b33-4cac-a568-4a4bf7a94f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only editar-icon botao-action-center ui-state-focus ui-state-hover</value>
      <webElementGuid>97b9446a-5b6f-4791-b737-17200f5ef51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmWithholdingMap:recipients:2:j_id_90&quot;,p:&quot;frmWithholdingMap:recipients:2:j_id_90&quot;,u:&quot;formAddRecipient&quot;});return false;</value>
      <webElementGuid>db2cb421-9843-4960-a9bc-668487270b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>6a8aa1e5-33b2-4f12-93f1-2be871356b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7052a775-ec3d-44bf-83c6-230af8b5e355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4b2a028-e838-473d-9d45-268847924b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7889df3d-2cad-4034-bee0-383df26e700b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>541c01cd-b882-46d9-8cd1-77001460e61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWithholdingMap:recipients:2:j_id_90&quot;)</value>
      <webElementGuid>dacbbdd8-81d0-4408-acdb-7be61b8b59c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='frmWithholdingMap:recipients:2:j_id_90']</value>
      <webElementGuid>6771a2bb-0a68-499b-b11c-4420694287d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td/button</value>
      <webElementGuid>ce269747-d835-4388-8dfa-4f066d579452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 32,50'])[1]/following::button[1]</value>
      <webElementGuid>6dbe21b0-aa6a-4cef-8882-cecb2e786676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 500,00'])[1]/following::button[1]</value>
      <webElementGuid>dfa6117c-6c48-4bf2-a290-1a56a7abe588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remover'])[3]/preceding::button[1]</value>
      <webElementGuid>ac2da1fa-8055-4771-ab71-74e6e4efa392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/button</value>
      <webElementGuid>e3c6b75c-6f65-488f-9d84-3c1f986e9887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'frmWithholdingMap:recipients:2:j_id_90' and @name = 'frmWithholdingMap:recipients:2:j_id_90' and @title = 'Editar' and @type = 'submit' and (text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>e65b91e0-93ba-4814-adee-74b03dd310f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
