<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_editar</name>
   <tag></tag>
   <elementGuidId>20735841-f700-4696-8f4a-428ff9332789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cad2dcb-8324-48dd-9cac-60a8e8c8968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar</value>
      <webElementGuid>c9ea499c-39ab-4d49-914b-43f4f32d4512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar</value>
      <webElementGuid>c1163bcf-92ac-498e-ad58-2479f5e6c8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only editar-icon float-none ui-state-focus ui-state-hover</value>
      <webElementGuid>7c8c7334-8fbc-4bab-af87-aab814513a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar&quot;,p:&quot;form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar&quot;,u:&quot;form-create:tabela-ii-mapa-retencao-na-fonte&quot;});return false;</value>
      <webElementGuid>59804f77-3b02-4ae3-9ec6-be0f5b173489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>21e965d4-fdf5-447f-a6fe-fe5c5f44b19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8e20b1de-f1d5-4971-9549-bd552a75b3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6fe26c0-4638-4ff5-9139-a9a2f9bf77e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27f924c1-c033-42cd-b300-dc88863e4906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>editar</value>
      <webElementGuid>06bb2774-7bab-4e57-8330-39d104cdeb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar&quot;)</value>
      <webElementGuid>05419463-babd-4dbb-8128-5d72596c777e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar']</value>
      <webElementGuid>4aeab3c7-cb1b-469f-a325-2faae0b65847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form-create:tabela-ii-mapa-retencao-na-fonte_data']/tr/td/button</value>
      <webElementGuid>c2f52d4e-1397-4732-ac3e-7fd1e6fbd5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentos'])[1]/following::button[1]</value>
      <webElementGuid>1a9f9cb6-0afb-4adf-9b93-dbc612524c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Estado'])[1]/following::button[1]</value>
      <webElementGuid>7bb9076b-d955-4b20-be66-19e70786207b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visualizar'])[1]/preceding::button[1]</value>
      <webElementGuid>1c7288b3-2c4c-46b4-a4f9-5a975a573444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>6ba69828-5c24-46fb-b42a-3e9719c618cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar' and @name = 'form-create:tabela-ii-mapa-retencao-na-fonte:0:btneditar' and @title = 'Editar' and @type = 'submit' and (text() = 'editar' or . = 'editar')]</value>
      <webElementGuid>38dfdb41-b5c3-4f70-91f6-c61a3853ffb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
