<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero da Factura_formAddRecipientinpu_cead7b</name>
   <tag></tag>
   <elementGuidId>d31a808f-671c-4f12-b4d5-41d5aae21c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'formAddRecipient:inputTextFacturaNumber' and @name = 'formAddRecipient:inputTextFacturaNumber' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formAddRecipient:inputTextFacturaNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19d8dd9d-133a-4289-9483-27d38352bcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formAddRecipient:inputTextFacturaNumber</value>
      <webElementGuid>57bba120-7323-4aae-b9e2-feb70ae5102a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formAddRecipient:inputTextFacturaNumber</value>
      <webElementGuid>cac42939-fae0-4820-984f-8646542fe62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5be14936-dead-4ab1-ab0a-c10d935ecc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-hover ui-state-focus</value>
      <webElementGuid>8c3a862a-8150-4489-9547-20ccd9329553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>8dcb7ddf-14d9-4ccf-9df4-ea8b5463e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>768b226a-3905-46b9-881d-73682277e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8da6ddbb-4e5b-42ec-a830-a7efcca2de5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddRecipient:inputTextFacturaNumber&quot;)</value>
      <webElementGuid>ecb403b4-0372-48b4-ba2e-a75d9f344ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formAddRecipient:inputTextFacturaNumber']</value>
      <webElementGuid>3761a916-31c1-45f5-8dfb-8ecb9612285e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddRecipient']/div/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>63b73185-0c56-4311-bd41-bcef3ff1fb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>494ee7cd-76b3-4287-9191-b03cd55b1d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'formAddRecipient:inputTextFacturaNumber' and @name = 'formAddRecipient:inputTextFacturaNumber' and @type = 'text']</value>
      <webElementGuid>63761ccb-9fe6-4595-aa9e-bddcc25deb90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
