<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Descrio do Servio_formAddRecipientj_id_g5</name>
   <tag></tag>
   <elementGuidId>7fa59f17-ef42-492f-9b2b-32fb812126b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formAddRecipient:j_id_g5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea5bcaa7-f3f9-407f-927f-b4ef36dde834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formAddRecipient:j_id_g5</value>
      <webElementGuid>f0e74432-5cbb-4a2d-a896-4d89a7f5952e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formAddRecipient:j_id_g5</value>
      <webElementGuid>1a70d12c-a7cd-4874-9b6f-6e9f7fec997d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d513cdf-aac3-4f07-9da1-27d00282b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-hover ui-state-focus</value>
      <webElementGuid>f7abaa6a-584a-4c59-98a9-ccc4654297fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bf1222dd-0fc0-4870-9a45-cd316dd39b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f363c25-2aca-4edb-ad97-8667ec7064a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bf57566-d23d-4d02-b5a3-2baf063306d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddRecipient:j_id_g5&quot;)</value>
      <webElementGuid>6e233052-5c4b-4380-a176-aefbe3e38b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formAddRecipient:j_id_g5']</value>
      <webElementGuid>16fcde04-3834-4517-99d2-571b672df13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddRecipient']/div/div[5]/div/div/div[3]/div/input</value>
      <webElementGuid>26c5c65c-0517-4e12-9959-2606f6b78de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div/input</value>
      <webElementGuid>21df51d0-d67b-4616-b2d8-c3e8c11d2fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'formAddRecipient:j_id_g5' and @name = 'formAddRecipient:j_id_g5' and @type = 'text']</value>
      <webElementGuid>d3b0e81b-737f-4cf2-8ab5-b55aba9d3dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
