<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmero Fiscal_formAddRecipientnifRecipient</name>
   <tag></tag>
   <elementGuidId>ddcba12d-8813-4dc5-9701-9e5b86dad6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='formAddRecipient:nifRecipient']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd952b9e-66ab-4980-be20-00cd5818536a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formAddRecipient:nifRecipient</value>
      <webElementGuid>2b28215d-b823-46a8-8dbf-a7a52c01f35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formAddRecipient:nifRecipient</value>
      <webElementGuid>62d2ddd7-877f-4e92-baae-c19ce7e160b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee23c586-2151-4cc2-ac5e-c0116b016060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>73db4f0b-7f65-4bff-b9ce-d8ecc7339b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;formAddRecipient:nifRecipient&quot;,e:&quot;change&quot;,p:&quot;formAddRecipient:nifRecipient&quot;,u:&quot;formAddRecipient&quot;});</value>
      <webElementGuid>c96b5701-fe46-4e10-bde4-957d8826e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-hover ui-state-focus</value>
      <webElementGuid>af3f45e1-c690-4541-9d4b-51db8c23b573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>7643b96c-2f85-430d-8a5d-b2dd0bace012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca6e4581-36cf-481c-a1d0-fd6c0ca02a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-val</name>
      <type>Main</type>
      <value>Size</value>
      <webElementGuid>d30d334b-6b43-4e03-851a-8dbb6e95a1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>132c974d-2ca8-484f-b871-26777e9094ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6d8c7f54-e7a0-4651-a303-4532f2fd735d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aab86d9c-dd00-430b-b3eb-879371156e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddRecipient:nifRecipient&quot;)</value>
      <webElementGuid>20e397d4-17ad-4753-9e0a-521de8c0f871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formAddRecipient:nifRecipient']</value>
      <webElementGuid>1e231e00-83e5-422c-ac24-b1d2cc2e1256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formAddRecipient:j_id_ew']/div/div/input</value>
      <webElementGuid>94dcd328-aaef-4b00-9dea-185d7471015b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d6107abe-36f7-4e1f-91b1-ed3bd4a2fe33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'formAddRecipient:nifRecipient' and @name = 'formAddRecipient:nifRecipient' and @type = 'text']</value>
      <webElementGuid>e0bcb60a-71cf-4394-b7f7-8082f2845371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
