<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Adicionar</name>
   <tag></tag>
   <elementGuidId>34430c5e-be62-4c20-80cd-27055a7d9870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='formAddRecipient:j_id_h2']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5019b2c5-39bb-49fa-aa51-11c45654b876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>0d98a779-0ff9-49ac-ab97-309b6d34f12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adicionar</value>
      <webElementGuid>621bc5d0-3534-4faf-9458-fc90bc7a62b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formAddRecipient:j_id_h2&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>daf90e8a-8951-4d23-9126-02afe0c3fba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='formAddRecipient:j_id_h2']/span</value>
      <webElementGuid>9f4d5f1e-f813-474e-8bf8-5f4dd0fb2362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imposto Retido'])[1]/following::span[1]</value>
      <webElementGuid>9e976e38-e0e8-4c1a-872a-231757ce8f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxa'])[1]/following::span[3]</value>
      <webElementGuid>80edc3a5-9b9d-4609-9a61-29e239fb39c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sair'])[3]/preceding::span[1]</value>
      <webElementGuid>2276cf05-f675-4e65-baf7-3d56cf8fb90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXCEL'])[2]/preceding::span[2]</value>
      <webElementGuid>9a983e46-aa6c-4d77-96ec-c97659f1e8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adicionar']/parent::*</value>
      <webElementGuid>0b4e6ff8-0c6f-4217-a4dd-eaf9ced67606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button/span</value>
      <webElementGuid>c0bbd10e-197b-44c7-8b7d-a0a34067ebed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Adicionar' or . = 'Adicionar')]</value>
      <webElementGuid>6497b6f0-4288-49c0-a8b2-e318fff8fc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
