<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_02022023</name>
   <tag></tag>
   <elementGuidId>a52df053-f1c9-4a98-928d-65c10103ca6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>05655f30-828e-47d2-a91d-978fc409dd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>2707ba21-9a01-4b27-8628-c10e55f726fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-width-100</value>
      <webElementGuid>3acbe6c1-c934-42f7-90c8-9ba12fcc1f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02/02/2023</value>
      <webElementGuid>7477a88f-fec9-4445-ada2-2763c3dc3fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWithholdingMap:recipients_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even&quot;]/td[@class=&quot;col-width-100&quot;]</value>
      <webElementGuid>a166f914-f0b6-4db5-a221-136aa8f21763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[10]</value>
      <webElementGuid>766b568e-3522-40f6-b33d-f954fdbec95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTESTE'])[1]/following::td[2]</value>
      <webElementGuid>b69fbba6-fa1d-452a-8518-dc73a06f56c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTX555555'])[1]/following::td[3]</value>
      <webElementGuid>c5225293-7727-474b-83b2-ced80347c689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[1]/preceding::td[1]</value>
      <webElementGuid>df38e076-bf5e-4af0-b5bf-e9363469e5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[2]/preceding::td[2]</value>
      <webElementGuid>2b6ba30d-a3f8-40ec-b827-6be944a43eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[10]</value>
      <webElementGuid>04ec1665-1c8b-4172-a2d3-f6b62fae3083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '02/02/2023' or . = '02/02/2023')]</value>
      <webElementGuid>72e8aedf-619e-4b1d-96e1-ad0040c8d6fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
