<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_22012023</name>
   <tag></tag>
   <elementGuidId>e1341429-eedc-4dea-b203-f03408a34ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>138ef081-5fe4-4b6a-aa3c-c2c14bd81122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>54dc14a2-37ac-4cd2-891b-3cae294e2fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-width-100</value>
      <webElementGuid>574f95ec-1866-47e1-988e-86ea8cde3bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22/01/2023</value>
      <webElementGuid>2e09da88-3ce3-4a3b-84fa-734e996273d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWithholdingMap:recipients_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even&quot;]/td[@class=&quot;col-width-100&quot;]</value>
      <webElementGuid>fc556f5b-5772-493d-82af-acfd45cf7458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[9]</value>
      <webElementGuid>ad97efdd-2ac0-487d-9a10-ca157c17f7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='teste'])[1]/following::td[1]</value>
      <webElementGuid>2310fd91-d992-4335-8a9f-82277d37caa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ft8888'])[1]/following::td[2]</value>
      <webElementGuid>82efaef4-92db-4f7b-b522-99cc2a9430fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[1]/preceding::td[2]</value>
      <webElementGuid>a1633f0c-1f1e-471e-ba85-d75bd310337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[2]/preceding::td[3]</value>
      <webElementGuid>c15af33e-b69a-49a7-8c73-d2fc0dd5cc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='22/01/2023']/parent::*</value>
      <webElementGuid>143ce2b9-dfda-4c27-8b10-67347fef8058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]</value>
      <webElementGuid>a53251a6-7c0a-4a4c-8753-3a4ff2f0ccf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '22/01/2023' or . = '22/01/2023')]</value>
      <webElementGuid>815797a8-b44c-4e10-ba38-4bd4d6877a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
