<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_23012023</name>
   <tag></tag>
   <elementGuidId>25fe1dea-f490-4956-85b0-cd08ebfdc7aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8f46b22e-35b4-4588-a592-969310eaa461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>ca5ba644-52a4-4b1a-861d-a10739f216d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-width-100</value>
      <webElementGuid>53f6b3a7-a659-4479-867a-9f3fff58e864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23/01/2023</value>
      <webElementGuid>72a41571-562f-42c1-8e04-d23726156961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWithholdingMap:recipients_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even&quot;]/td[@class=&quot;col-width-100&quot;]</value>
      <webElementGuid>8b9626a8-bd38-40e4-bd7c-a987baa34fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='frmWithholdingMap:recipients_data']/tr[3]/td[9]</value>
      <webElementGuid>5a26bbb3-d1bd-4a15-846d-c06377012cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTESTE'])[1]/following::td[1]</value>
      <webElementGuid>294460db-7861-4af9-9c0c-f3bc14b3532a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTX555555'])[1]/following::td[2]</value>
      <webElementGuid>9cd0fdd9-8313-4aca-86be-8068b4324d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[1]/preceding::td[2]</value>
      <webElementGuid>957550b9-c27e-4ec2-bcb5-97c1a49da277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kz 0,00'])[2]/preceding::td[3]</value>
      <webElementGuid>1afd870a-5f81-4ee9-93bb-f6a5d623f121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23/01/2023']/parent::*</value>
      <webElementGuid>b4df2aa5-4671-41f4-ac04-b764d6a1c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[9]</value>
      <webElementGuid>b37c6c9e-a120-4c08-abbb-588b0cf3fb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '23/01/2023' or . = '23/01/2023')]</value>
      <webElementGuid>dc07b5e9-c512-46ce-bd91-39a3f15dde00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
