<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_j_id_o</name>
   <tag></tag>
   <elementGuidId>c951bcdf-f9dc-4fca-b21f-9e645106a4ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_id_o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_id_o']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc12c8f9-c128-4084-a8bf-58b351214d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_id_o</value>
      <webElementGuid>8a81c673-75a0-4f79-b28c-a2a22979a4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_id_o</value>
      <webElementGuid>275db86d-c1d1-4e41-bd4d-b5800d5d880b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa6a4081-62a8-4797-ba45-000022570f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Iniciar Sessão</value>
      <webElementGuid>70d4753e-22eb-4cdf-b18e-c5129cc1f0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>c8445bcb-0c1f-4c71-a126-e87916871b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_id_o&quot;)</value>
      <webElementGuid>aba65811-4343-4785-b72b-2b0d2be9b867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_id_o']</value>
      <webElementGuid>aae396d7-0ba1-4994-b27b-247c019bd9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/form/div/div[3]/input</value>
      <webElementGuid>b2981a8b-9d06-4188-9e05-caa7297f6e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f27d9d39-8379-498c-aed9-016b06264501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_id_o' and @name = 'j_id_o' and @type = 'submit']</value>
      <webElementGuid>86db19e1-cc3c-480d-b1c3-a1bf799fbbfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
